name: Publish LabAide to Maven repository
run-name: Deploy to Maven repo by @${{ github.actor }}
on: [ workflow_dispatch ]
jobs:
  publish:
    name: Publish [mvn-snapshot]
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Set up maven credentials
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "arcadelabs-repository-snapshots", "username": "${{ secrets.REPO_NAME }}", "password": "${{ secrets.REPO_TOKEN }}"}]'
      - name: Publish with Maven
        run: mvn deploy
